import axios from "axios";

/**
 * Syncs a task and its subtasks/roadmaps to a new Google Tasks checklist list.
 */
export const syncToGoogleTasks = async (task, token) => {
  const headers = {
    Authorization: `Bearer ${token}`,
    "Content-Type": "application/json",
  };
  
  // 1. Create a custom task list for the task
  const listResponse = await axios.post(
    "https://tasks.googleapis.com/v1/users/@me/lists",
    { title: `DoNext: ${task.title}` },
    { headers }
  );
  
  const listId = listResponse.data.id;
  
  // 2. Add each subtask as an item inside the list
  if (task.subtasks && task.subtasks.length > 0) {
    for (const subtask of task.subtasks) {
      await axios.post(
        `https://tasks.googleapis.com/v1/lists/${listId}/tasks`,
        {
          title: subtask.title,
          status: subtask.completed ? "completed" : "needsAction",
        },
        { headers }
      );
    }
  }
  return listResponse.data;
};

/**
 * Searches the user's primary calendar to find the first free 30-minute slot
 * and schedules a Focus study event block.
 */
export const scheduleOnGoogleCalendar = async (task, token) => {
  const headers = {
    Authorization: `Bearer ${token}`,
    "Content-Type": "application/json",
  };

  const now = new Date();
  const timeMin = now.toISOString();
  const timeMax = new Date(now.getTime() + 8 * 60 * 60 * 1000).toISOString(); // Look ahead 8 hours

  // Query busy times
  const freebusyRes = await axios.post(
    "https://www.googleapis.com/calendar/v3/freebusy",
    {
      timeMin,
      timeMax,
      items: [{ id: "primary" }],
    },
    { headers }
  );

  const busySlots = freebusyRes.data.calendars.primary.busy || [];
  
  // Align search starting time to the next 30-minute interval
  let start = new Date(now.getTime() + 30 * 60 * 1000); 
  start.setMinutes(Math.ceil(start.getMinutes() / 30) * 30, 0, 0);
  
  let found = false;
  let attempt = 0;
  // Test slots over the 8 hour horizon
  while (!found && attempt < 16) {
    const slotStart = new Date(start.getTime() + attempt * 30 * 60 * 1000);
    const slotEnd = new Date(slotStart.getTime() + 30 * 60 * 1000);
    
    const isOverlap = busySlots.some((busy) => {
      const busyStart = new Date(busy.start);
      const busyEnd = new Date(busy.end);
      return slotStart < busyEnd && slotEnd > busyStart;
    });

    if (!isOverlap) {
      start = slotStart;
      found = true;
      break;
    }
    attempt++;
  }

  const end = new Date(start.getTime() + 30 * 60 * 1000);

  // Insert calendar event
  const eventRes = await axios.post(
    "https://www.googleapis.com/calendar/v3/calendars/primary/events",
    {
      summary: `DoNext Focus: ${task.title}`,
      description: `Focus study block synchronized by DoNext AI.\n\nDescription: ${task.description || "No notes"}`,
      start: { dateTime: start.toISOString() },
      end: { dateTime: end.toISOString() },
    },
    { headers }
  );

  return eventRes.data;
};

/**
 * Creates a Google Calendar event containing a Google Meet conference space link.
 */
export const createGoogleMeetRoom = async (task, token) => {
  const headers = {
    Authorization: `Bearer ${token}`,
    "Content-Type": "application/json",
  };

  const now = new Date();
  const end = new Date(now.getTime() + 30 * 60 * 1000); // Default 30 min duration

  const response = await axios.post(
    "https://www.googleapis.com/calendar/v3/calendars/primary/events?conferenceDataVersion=1",
    {
      summary: `DoNext Meet: ${task.title}`,
      description: `Collaborative study workspace room generated by DoNext AI for: ${task.title}`,
      start: { dateTime: now.toISOString() },
      end: { dateTime: end.toISOString() },
      conferenceData: {
        createRequest: {
          requestId: `meet-${Date.now()}`,
          conferenceSolutionKey: { type: "hangoutsMeet" },
        },
      },
    },
    { headers }
  );

  const entryPoints = response.data.conferenceData?.entryPoints || [];
  const videoEntryPoint = entryPoints.find((ep) => ep.entryPointType === "video");
  
  if (!videoEntryPoint) {
    throw new Error("Failed to generate Google Meet video room link.");
  }

  return {
    meetingUrl: videoEntryPoint.uri,
    eventUrl: response.data.htmlLink,
  };
};

/**
 * Helper to convert 2D array row cell formats to Google Sheets API structure
 */
const convertToRowData = (rows) => {
  return rows.map((row) => ({
    values: row.map((cell) => {
      if (typeof cell === "number") {
        return { userEnteredValue: { numberValue: cell } };
      } else if (typeof cell === "boolean") {
        return { userEnteredValue: { boolValue: cell } };
      } else {
        return { userEnteredValue: { stringValue: String(cell) } };
      }
    }),
  }));
};

/**
 * Exports current roadmaps list and badges achievements data into a new Google Spreadsheet.
 */
export const exportStatsToGoogleSheets = async (tasks, achievements, token) => {
  const headers = {
    Authorization: `Bearer ${token}`,
    "Content-Type": "application/json",
  };

  // Convert roadmap items
  const roadmapHeaders = [
    "Task Title",
    "Description",
    "Deadline",
    "Priority",
    "Completed Status",
    "Subtasks Done",
    "Total Subtasks"
  ];
  const taskRows = tasks.map((t) => {
    const subtasksDone = t.subtasks ? t.subtasks.filter((st) => st.completed).length : 0;
    const subtasksTotal = t.subtasks ? t.subtasks.length : 0;
    return [
      t.title,
      t.description || "",
      t.deadline,
      t.priority,
      t.completed ? "Completed" : "Active",
      subtasksDone,
      subtasksTotal
    ];
  });
  const roadmapRowData = convertToRowData([roadmapHeaders, ...taskRows]);

  // Convert achievements items
  const achievementsHeaders = ["Productivity Badge / Achievement", "Unlocked Status"];
  const achievementsRows = [
    ["Voice Pioneer (Dictated a Task with Voice)", achievements.voicePioneer ? "Unlocked" : "Locked"],
    ["Focus Master (Completed Pomodoro Focus Session)", achievements.focusMaster ? "Unlocked" : "Locked"],
    ["Calendar Sync (Connected Google Calendar)", achievements.calendarSync ? "Unlocked" : "Locked"],
    ["Deadline Conqueror (Completed a High Priority Task)", achievements.deadlineConqueror ? "Unlocked" : "Locked"]
  ];
  const achievementsRowData = convertToRowData([achievementsHeaders, ...achievementsRows]);

  // Create spreadsheet request
  const response = await axios.post(
    "https://sheets.googleapis.com/v4/spreadsheets",
    {
      properties: {
        title: `DoNext AI: Productivity Stats (${new Date().toLocaleDateString()})`
      },
      sheets: [
        {
          properties: { title: "Roadmap Tasks" },
          data: [{ startRow: 0, startColumn: 0, rowData: roadmapRowData }]
        },
        {
          properties: { title: "Achievements Log" },
          data: [{ startRow: 0, startColumn: 0, rowData: achievementsRowData }]
        }
      ]
    },
    { headers }
  );

  return response.data;
};
